### ISSUE TITLE
Is it possible to  use chakra-host using XAML's CanvasControl and the WebGL framework to create a Win 10 UWP c# app

### ISSUE THREAD

**Issue by JimSEOW** [panopticoncentral/chakra-host#4]
http://stackoverflow.com/questions/35390441/embedding-chakrahost-c-for-webgl-example

**Comment by panopticoncentral** [comment]
This is a little beyond the scope of this example. Looking a bit at the question, it looks like there's an additional something that handles the shader script blocks in the browser, I'm not sure how you'd hook that in, unfortunately.
